import { IEqualizerBand } from "moonlink.js/dist/src/typings/Interfaces";

// Each preset is an array of 15 bands (0-14)
export const EQPresets: Record<string, IEqualizerBand[]> = {
    Rock: [
        { band: 0, gain: 0.25 },
        { band: 1, gain: 0.25 },
        { band: 2, gain: 0.2 },
        { band: 3, gain: 0.2 },
        { band: 4, gain: 0.15 },
        { band: 5, gain: 0.1 },
        { band: 6, gain: 0 },
        { band: 7, gain: -0.05 },
        { band: 8, gain: -0.1 },
        { band: 9, gain: -0.1 },
        { band: 10, gain: 0 },
        { band: 11, gain: 0.1 },
        { band: 12, gain: 0.15 },
        { band: 13, gain: 0.2 },
        { band: 14, gain: 0.25 },
    ],
    BassBoost: [
        { band: 0, gain: 0.5 },
        { band: 1, gain: 0.45 },
        { band: 2, gain: 0.4 },
        { band: 3, gain: 0.35 },
        { band: 4, gain: 0.25 },
        { band: 5, gain: 0.15 },
        { band: 6, gain: 0 },
        { band: 7, gain: -0.05 },
        { band: 8, gain: -0.1 },
        { band: 9, gain: -0.15 },
        { band: 10, gain: -0.2 },
        { band: 11, gain: -0.15 },
        { band: 12, gain: -0.1 },
        { band: 13, gain: -0.05 },
        { band: 14, gain: 0 },
    ],
    Pop: [
        { band: 0, gain: -0.1 },
        { band: 1, gain: -0.05 },
        { band: 2, gain: 0 },
        { band: 3, gain: 0.05 },
        { band: 4, gain: 0.1 },
        { band: 5, gain: 0.15 },
        { band: 6, gain: 0.2 },
        { band: 7, gain: 0.2 },
        { band: 8, gain: 0.15 },
        { band: 9, gain: 0.1 },
        { band: 10, gain: 0 },
        { band: 11, gain: -0.05 },
        { band: 12, gain: -0.05 },
        { band: 13, gain: 0 },
        { band: 14, gain: 0.05 },
    ],
    Jazz: [
        { band: 0, gain: 0 },
        { band: 1, gain: 0 },
        { band: 2, gain: 0.1 },
        { band: 3, gain: 0.15 },
        { band: 4, gain: 0.2 },
        { band: 5, gain: 0.2 },
        { band: 6, gain: 0.15 },
        { band: 7, gain: 0.1 },
        { band: 8, gain: 0 },
        { band: 9, gain: -0.05 },
        { band: 10, gain: -0.1 },
        { band: 11, gain: -0.1 },
        { band: 12, gain: -0.05 },
        { band: 13, gain: 0 },
        { band: 14, gain: 0 },
    ],
    Deep: [
        { band: 0, gain: 0.4 },
        { band: 1, gain: 0.35 },
        { band: 2, gain: 0.3 },
        { band: 3, gain: 0.25 },
        { band: 4, gain: 0.2 },
        { band: 5, gain: 0.15 },
        { band: 6, gain: 0.1 },
        { band: 7, gain: 0 },
        { band: 8, gain: -0.05 },
        { band: 9, gain: -0.1 },
        { band: 10, gain: -0.15 },
        { band: 11, gain: -0.2 },
        { band: 12, gain: -0.25 },
        { band: 13, gain: -0.3 },
        { band: 14, gain: -0.35 },
    ],
    Flat: Array(15).fill(0).map((_, i) => ({ band: i, gain: 0 })),
    HipHop: [
        { band: 0, gain: 0.5 },
        { band: 1, gain: 0.45 },
        { band: 2, gain: 0.4 },
        { band: 3, gain: 0.35 },
        { band: 4, gain: 0.3 },
        { band: 5, gain: 0.2 },
        { band: 6, gain: 0.1 },
        { band: 7, gain: 0 },
        { band: 8, gain: -0.1 },
        { band: 9, gain: -0.15 },
        { band: 10, gain: -0.2 },
        { band: 11, gain: -0.15 },
        { band: 12, gain: -0.1 },
        { band: 13, gain: -0.05 },
        { band: 14, gain: 0 },
    ],
    Classical: [
        { band: 0, gain: -0.1 },
        { band: 1, gain: -0.05 },
        { band: 2, gain: 0 },
        { band: 3, gain: 0.05 },
        { band: 4, gain: 0.1 },
        { band: 5, gain: 0.15 },
        { band: 6, gain: 0.2 },
        { band: 7, gain: 0.25 },
        { band: 8, gain: 0.2 },
        { band: 9, gain: 0.15 },
        { band: 10, gain: 0.1 },
        { band: 11, gain: 0.05 },
        { band: 12, gain: 0 },
        { band: 13, gain: -0.05 },
        { band: 14, gain: -0.1 },
    ],
    SpokenWord: [
        { band: 0, gain: 0 },
        { band: 1, gain: 0 },
        { band: 2, gain: 0 },
        { band: 3, gain: 0 },
        { band: 4, gain: 0 },
        { band: 5, gain: 0.05 },
        { band: 6, gain: 0.1 },
        { band: 7, gain: 0.1 },
        { band: 8, gain: 0.05 },
        { band: 9, gain: 0 },
        { band: 10, gain: -0.05 },
        { band: 11, gain: -0.1 },
        { band: 12, gain: -0.1 },
        { band: 13, gain: -0.05 },
        { band: 14, gain: 0 },
    ]
};
